# Generated by Django 3.2.13 on 2022-06-29 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(5000)]),
        ),
    ]
