# Generated by Django 3.2.13 on 2022-06-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='name',
            new_name='first_name',
        ),
    ]
